# Options for analysis running.
run:
  timeout: 1m
  tests: true
  exclude-dirs:
    - sql
    - proto
    - gen
    - build
    - bin
    - cmd/grpc_gateway/gen
    - internal/mock
  go: "1.24"
# output configuration options
output:
  sort-results: true
linters:
  disable:
    - gci
    - exhaustive
    - exhaustruct
    - paralleltest
    - wrapcheck
    - forbidigo
    - gochecknoglobals
    - depguard
    - tagalign
    - musttag
    - dupword
  enable:
    - gocyclo
  presets:
    - bugs
    - unused
    - test
    - import
    - error
    - performance
    # - style
    - format
    - comment
    - complexity
linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
issues:
  skip-dirs-use-default: true
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
