name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Cyclomatic Complexity Checker
        run: make cc

      - name: Test
        run: make test COVER_PROFILE_FILE=cover.out

      - name: Coverage Check
        run: make check.coverage COVER_PROFILE_FILE=cover.out
