name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Test Tools
        run: make install-test-tools

      - name: Lint
        run: make lint

      - name: Vulnerability Check
        run: make vuln

      - name: Test
        run: make test-complete COVER_PROFILE_FILE=cover.out

      # disable for now, need some research to get the total coverage
      # - name: Coverage Check
      #   run: make check.coverage COVER_PROFILE_FILE=cover.out
